### ISSUE TITLE
关于项目

### ISSUE THREAD

**Issue by nlpser** [jolemon/ML-Microservice-Architecture#1]
您好，请问您的BLESER项目是删除了吗？我对您的这篇文章非常感兴趣。请问大概什么时候会重新发布呢？请问可以和您进行交流吗？非常抱歉打扰您了。

**Comment by jolemon** [comment]
项目还处于实验阶段，所以几个月内不方便公开，问题可以联系我的邮箱 728385437@qq.com ，我尽力回复，谢谢！
